#!/bin/bash

sudo echo | grep -q a

for ((i=1; i<=5; i++)); do
    case ${!i} in
        \-*)
            if [[ "${!i}" == *b* ]]; then
                option=backup
            fi

            if [[ "${!i}" == *h* ]]; then
                option=help
            fi

            if [[ "${!i}" == *d* ]]; then
                rsyncoptions=(${rsyncoptions}-n )
            fi

            if [[ "${!i}" == *r* ]]; then
                rsyncoptions=(${rsyncoptions}--delete )
            fi

            if [[ "${!i}" == *p* ]]; then
                rsyncoptions=(${rsyncoptions}--progress )
            fi

            if [[ "${!i}" == *s* ]]; then
                option=show
            fi
        ;;

        /*)
            if [[ -z $bp ]]; then
                bp="${!i}"
            else
                tp="${!i}"
            fi
        ;;

        *)
            if [[ -b /dev/${!i} ]]; then
                if [[ -z $bp ]]; then
                    bdp="/dev/${!i}"
                else
                    tdp="/dev/${!i}"
                fi
            fi
        ;;
    esac
done

case $option in
    backup)
        if [[ ! -e $bp ]] || [[ -z $tp ]]; then
            echo "Type in 'saver -h' to see the list of commands"
            exit
        fi

        fbp=$bp
        ftp=$tp

        if [[ ! -z $bdp ]]; then
            sudo umount $bdp | grep -q a
            sudo mkdir /mnt/saverbd | grep -q a
            sudo mount  $bdp /mnt/saverbd
            fbp=/mnt/saverbd${bp}
        fi

        if [[ ! -z $tdp ]]; then
            sudo umount $tdp | grep -q a
            sudo mkdir /mnt/savertd | grep -q a
            sudo mount $tdp /mnt/savertd
            ftp=/mnt/savertd${tp}
        fi

        [[ ! -e $tp ]] && mkdir -p $ftp
      
        sudo rsync -aAXv "${rsyncoptions[@]}" $fbp --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} $ftp

        if [[ ! -z $bdp ]]; then
            sudo umount $bdp | grep -q a
            sudo rm -rf /mnt/saverd 
        fi

        if [[ ! -z $tdp ]]; then
            sudo umount $tdp | grep -q a
            sudo rm -rf /mnt/savertd 
        fi
    ;;

    show)
        lsblk -o NAME,SIZE,MOUNTPOINT | tail -n +2
    ;;

    help)
        echo -e "\n This program will automaticly exclude these directories\n from syncing: /dev ; /proc ; /sys ; /tmp ; /run ; /mnt ; /media ; /lost+found.\n You should type in ONLY the name of a disk WITHOUT '/dev/' at the beginning. The program will add it automatically for you.\n Any external disk you mention will be unmounted at the end of the program."
        echo -e "\n Options:"
        echo -e "\n -b     Sync folders. Usage: saver -b (disk to sync from, empty for current disk) (path to sync from) (target disk, empty for current disk) (target path)" 
        echo -e "  -r     Remove files from the target directory which aren't present in the path you're syncing from"
        echo -e "  -d     Preform a 'dry run', which means that nothing is really going to happen, but you'd be able to see which files would've been synced"
        echo -e "  -p     Display progress for individual files (useful for large files)"
        echo -e " -s     Show available disks/partitions"
        echo -e " -h     Show this help"
        echo
    ;;

    *)
        echo "Type in 'saver -h' to see the list of commands"
    ;;
esac

